### ISSUE TITLE
Cell width overflows

### ISSUE THREAD

**Issue by ooker777** [tomaszkiewicz/obsidian-database-plugin#19]
I set the width to only 1% but it still overflows
```
fields:
- name: file
  type: fileName
  label: Công việc cấp ban
  width: 1%
```
![](https://i.imgur.com/kPcCDsD.png)
