### ISSUE TITLE
[feature]: support for other data types

### ISSUE THREAD

**Issue by imeed166** [tomaszkiewicz/obsidian-database-plugin#5]
- checkbox type
- date type
- multi-select type
- image type

**Comment by tomaszkiewicz** [comment]
At the moment, some of the HTML input field types (https://www.w3schools.com/tags/tag_input.asp) are supported out-of-the-box:

E.g.: date, color:

```yaml
fields:
- name: color
  type: color
- name: reviewDate
  label: Review date
  type: date
```
Checkbox is handled a little diffrently so I need to implement it separately.

For image and multi-select - I'll think how to implement that in a nice way :)
